const tvTitles = [
  "13 Reasons Why",
  "24",
  "30 Rock",
  "Adventure Time",
  "Altered Carbon",
  "American Crime Story",
  "American Horror Story",
  "Andor",
  "Anne with an E",
  "Arcane",
  "Arrested Development",
  "Arrow",
  "Atlanta",
  "Attack on Titan",
  "Avatar: The Last Airbender",
  "Band of Brothers",
  "Barry",
  "Bates Motel",
  "Battlestar Galactica (1978)",
  "Battlestar Galactica (2004)",
  "Better Call Saul",
  "Big Little Lies",
  "Billions",
  "Black Mirror",
  "Blackadder",
  "Bleach",
  "Boardwalk Empire",
  "BoJack Horseman",
  "Bones",
  "Breaking Bad",
  "Bridgerton",
  "Brooklyn Nine-Nine",
  "Buffy the Vampire Slayer",
  "Castle",
  "Charmed (1998)",
  "Charmed (2018)",
  "Chernobyl",
  "Chilling Adventures of Sabrina",
  "Chucky",
  "Community",
  "Cowboy Bebop",
  "Criminal Minds",
  "CSI: Crime Scene Investigation",
  "Curb Your Enthusiasm",
  "Dark",
  "Dark Desire",
  "Deadwood",
  "Death Note",
  "Demon Slayer",
  "Dexter",
  "Dexter: New Blood",
  "Doctor Who (1963)",
  "Doctor Who (2005)",
  "Dragon Ball Super",
  "Dragon Ball Z",
  "El Señor de los Cielos",
  "Elite",
  "Euphoria",
  "Ex Machina",
  "Fallout",
  "Family Guy",
  "Fargo",
  "Fear the Walking Dead",
  "Firefly",
  "Fleabag",
  "Freaks and Geeks",
  "Friends",
  "Fringe",
  "FROM",
  "Fullmetal Alchemist (2003)",
  "Fullmetal Alchemist: Brotherhood (2009)",
  "Futurama",
  "Game of Thrones",
  "Gilmore Girls",
  "Gossip Girl (2007)",
  "Gossip Girl (2021)",
  "Gotham",
  "Grey's Anatomy",
  "Grimm",
  "Hannibal",
  "Hawaii Five-0",
  "Hawkeye",
  "Homeland",
  "House",
  "House of Cards",
  "House of the Dragon",
  "How I Met Your Mother",
  "Hunter x Hunter",
  "INVINCIBLE",
  "It's Always Sunny in Philadelphia",
  "JUJUTSU KAISEN",
  "Justified",
  "Killing Eve",
  "Law & Order: Special Victims Unit",
  "Legion",
  "Loki",
  "Lost",
  "Love, Death & Robots",
  "Lucifer",
  "MacGyver (1985)",
  "MacGyver (2016)",
  "Mad Men",
  "Magnum P.I. (1980)",
  "Magnum P.I. (2018)",
  "Malcolm in the Middle",
  "Marvel's Agents of S.H.I.E.L.D.",
  "Marvel's Daredevil",
  "MINDHUNTER",
  "Miraculous: Tales of Ladybug & Cat Noir",
  "Modern Family",
  "Money Heist",
  "Moon Knight",
  "Mr. Robot",
  "My Hero Academia",
  "Narcos",
  "Naruto",
  "Naruto Shippūden",
  "NCIS",
  "New Girl",
  "One Piece",
  "One-Punch Man",
  "Outlander",
  "Ozark",
  "Pablo Escobar: The Drug Lord",
  "Parks and Recreation",
  "Peaky Blinders",
  "Peep Show",
  "Perry Mason (1957)",
  "Perry Mason (2020)",
  "Prison Break",
  "Rebelde",
  "Rick and Morty",
  "Riverdale",
  "Roswell (1999)",
  "Roswell, New Mexico (2019)",
  "Sabrina the Teenage Witch (1996)",
  "Scandal",
  "Schitt's Creek",
  "Scorpion",
  "Scrubs",
  "Seinfeld",
  "Sense8",
  "Severance",
  "Sherlock",
  "Silicon Valley",
  "Six Feet Under",
  "Smallville",
  "Sons of Anarchy",
  "South Park",
  "Spartacus",
  "Squid Game",
  "Stranger Things",
  "Succession",
  "Suits",
  "Supergirl",
  "Supernatural",
  "Ted Lasso",
  "Teen Wolf",
  "The 100",
  "The Act",
  "The Americans",
  "The Bear",
  "The Big Bang Theory",
  "The Blacklist",
  "The Boys",
  "The Crown",
  "The End of the F***ing World",
  "The Expanse",
  "The Falcon and the Winter Soldier",
  "The Flash (1990)",
  "The Flash (2014)",
  "The Good Doctor",
  "The Good Place",
  "The Handmaid's Tale",
  "The Haunting of Hill House",
  "The Last of Us",
  "The Lord of the Rings: The Rings of Power",
  "The Mandalorian",
  "The Marvelous Mrs. Maisel",
  "The Mentalist",
  "The Office (UK)",
  "The Office (US)",
  "The Originals",
  "The Queen's Gambit",
  "The Seven Deadly Sins",
  "The Shield",
  "The Simpsons",
  "The Sopranos",
  "The Twilight Zone (1959)",
  "The Twilight Zone (2019)",
  "The Umbrella Academy",
  "The Vampire Diaries",
  "The Walking Dead",
  "The White Lotus",
  "The Wire",
  "The Witcher",
  "The X-Files",
  "True Blood",
  "True Detective",
  "Twin Peaks",
  "Two and a Half Men",
  "Under the Dome",
  "Veep",
  "WandaVision",
  "Watchmen",
  "Wednesday",
  "Westworld",
  "What If...?",
  "Yellowjackets",
  "Yellowstone",
  "You",
  "11.22.63",
  "1883",
  "1899",
  "1923",
  "2 Broke Girls",
  "3 Body Problem",
  "3rd Rock from the Sun",
  "9-1-1",
  "9-1-1: Lone Star",
  "A Discovery of Witches",
  "A Very English Scandal",
  "Abbott Elementary",
  "ALF",
  "Alias",
  "Alice in Borderland",
  "All Creatures Great and Small (1978)",
  "All Creatures Great and Small (2020)",
  "All in the Family",
  "Ally McBeal",
  "American Crime",
  "American Dad!",
  "American Gods",
  "American Rust",
  "American Vandal",
  "Angel",
  "Angie Tribeca",
  "Animal Kingdom",
  "Animaniacs (1993)",
  "Animaniacs (2020)",
  "Archer",
  "Are You Afraid of the Dark? (1990)",
  "Around the World in 80 Days (2021)",
  "Ash vs Evil Dead",
  "Awkward",
  "Babylon 5",
  "Babylon Berlin",
  "Bad Sisters",
  "Banshee",
  "Barbarians",
  "Batwoman",
  "Baywatch",
  "Being Human (UK)",
  "Being Human (US)",
  "Below Deck",
  "Ben 10 (2005)",
  "Ben 10 (2016)",
  "Berserk (1997)",
  "Berserk (2016)",
  "Better Off Ted",
  "Bewitched",
  "Beyond Belief: Fact or Fiction",
  "Big Love",
  "Black Books",
  "Black Clover",
  "Black Lagoon",
  "Black Lightning",
  "Black Sails",
  "Black Summer",
  "Black-ish",
  "Blindspot",
  "Bloodline",
  "Blue Bloods",
  "Bluey",
  "Bob Hearts Abishola",
  "Bob's Burgers",
  "Bodyguard (2018)",
  "Borgen",
  "Bosch",
  "Boston Legal",
  "Boston Public",
  "Boy Meets World",
  "Brass Eye",
  "Broad City",
  "Broadchurch",
  "Bull",
  "Burn Notice",
  "Californication",
  "Call the Midwife",
  "Carnivàle",
  "Castle Rock",
  "Catastrophe",
  "Catfish: The TV Show",
  "Cheers",
  "Chicago Fire",
  "Chicago Med",
  "Chicago P.D.",
  "Chuck",
  "Clarice",
  "Clannad",
  "Claymore",
  "Cloak & Dagger",
  "Code Black",
  "Code Geass",
  "Cold Case",
  "Columbo",
  "Continuum",
  "Cougar Town",
  "Covert Affairs",
  "Cracker",
  "Crash Landing on You",
  "Crazy Ex-Girlfriend",
  "Criminal Minds: Evolution",
  "Crossing Jordan",
  "Cyberpunk: Edgerunners",
  "Damages",
  "Dark Angel",
  "Dark Winds",
  "Dawson's Creek",
  "Dead Like Me",
  "Dead Ringers (2023)",
  "Dead to Me",
  "Deadly Class",
  "Death in Paradise",
  "Defending Jacob",
  "Degrassi: The Next Generation",
  "Derry Girls",
  "Designated Survivor",
  "Desperate Housewives",
  "Devious Maids",
  "Dharma & Greg",
  "Digimon Adventure (1999)",
  "Dirk Gently's Holistic Detective Agency",
  "Doc Martin",
  "Dollhouse",
  "Doogie Howser, M.D.",
  "Doom Patrol",
  "Downton Abbey",
  "Dracula (2020)",
  "Drake & Josh",
  "Drop Dead Diva",
  "Dynasty (1981)",
  "Dynasty (2017)",
  "Early Edition",
  "Eastbound & Down",
  "Echo (2024)",
  "Elementary",
  "Entourage",
  "Episodes",
  "ER",
  "Erased",
  "Escape at Dannemora",
  "Eureka",
  "Everwood",
  "Everybody Hates Chris",
  "Everybody Loves Raymond",
  "Evil",
  "Family Matters",
  "Family Ties",
  "Farscape",
  "Fate/Zero",
  "Fawlty Towers",
  "FBI",
  "FBI: Most Wanted",
  "Feud",
  "Flight of the Conchords",
  "Flipper (1964)",
  "Flipper (1995)",
  "Foyle's War",
  "Frasier (1993)",
  "Frasier (2023)",
  "Fresh Off the Boat",
  "Full House",
  "Fuller House",
  "General Hospital",
  "Generation Kill",
  "Ghost Whisperer",
  "Ghosts (UK)",
  "Ghosts (US)",
  "Glee",
  "GLOW",
  "Gomorrah",
  "Good Omens",
  "Good Times",
  "Grace and Frankie",
  "Great Expectations (2023)",
  "Greenleaf",
  "Grown-ish",
  "Guilt",
  "Gunsmoke",
  "Hacks",
  "Happy Days",
  "Happy Endings",
  "Happy Valley",
  "Hart to Hart",
  "Haven",
  "Heartstopper",
  "Hell on Wheels",
  "Hellsing (2001)",
  "Hellsing Ultimate",
  "Heroes",
  "Heroes Reborn",
  "High Maintenance",
  "Hill Street Blues",
  "His Dark Materials",
  "Hogan's Heroes",
  "Home Improvement",
  "Homicide: Life on the Street",
  "How to Get Away with Murder",
  "Human Resources",
  "I Dream of Jeannie",
  "I Love Lucy",
  "I May Destroy You",
  "iCarly (2007)",
  "iCarly (2021)",
  "In Treatment",
  "Inuyasha",
  "Invader Zim",
  "Iron Fist",
  "It's a Sin",
  "Jane the Virgin",
  "Jericho (2006)",
  "Jessica Jones",
  "JoJo's Bizarre Adventure",
  "Jury Duty",
  "Just Shoot Me!",
  "Justified: City Primeval",
  "Kidding",
  "Killjoys",
  "King of the Hill",
  "Kingdom (2014)",
  "Kingdom (2019)",
  "Knight Rider (1982)",
  "Knight Rider (2008)",
  "Kojak (1973)",
  "Kojak (2005)",
  "Laverne & Shirley",
  "Law & Order",
  "Law & Order: Criminal Intent",
  "Law & Order: Organized Crime",
  "Legends of Tomorrow",
  "Leverage",
  "Leverage: Redemption",
  "Lie to Me",
  "Life on Mars (UK)",
  "Life on Mars (US)",
  "Line of Duty",
  "Little Britain",
  "Little Fires Everywhere",
  "Living Single",
  "Lizzie McGuire",
  "Locke & Key",
  "Longmire",
  "Lost in Space (1965)",
  "Lost in Space (2018)",
  "Louie",
  "Lovecraft Country",
  "Lovesick",
  "Luke Cage",
  "Luther",
  "M*A*S*H",
  "Mad About You",
  "Madam Secretary",
  "Made in Abyss",
  "Manifest",
  "Mare of Easttown",
  "Married... with Children",
  "Masters of Sex",
  "Masters of the Universe: Revelation",
  "Medium",
  "Melrose Place (1992)",
  "Melrose Place (2009)",
  "Miami Vice",
  "Midnight Mass",
  "Mike & Molly",
  "Mind Your Language",
  "Misfits",
  "Mob Psycho 100",
  "Monk",
  "Monster (2004)",
  "Mork & Mindy",
  "Mr. Bean",
  "Mr. Inbetween",
  "Mr. Mayor",
  "Ms. Marvel",
  "Murder, She Wrote",
  "Murphy Brown",
  "My Name Is Earl",
  "Mythic Quest",
  "Nashville",
  "NCIS: Hawai'i",
  "NCIS: Los Angeles",
  "NCIS: New Orleans",
  "Neon Genesis Evangelion",
  "New Amsterdam (2018)",
  "NewsRadio",
  "Night Court (1984)",
  "Night Court (2023)",
  "Nip/Tuck",
  "Normal People",
  "Northern Exposure",
  "Numb3rs",
  "NYPD Blue",
  "Once Upon a Time",
  "One Day (2024)",
  "One Tree Hill",
  "Only Murders in the Building",
  "Orange Is the New Black",
  "Orphan Black",
  "Orphan Black: Echoes",
  "Our Flag Means Death",
  "Outer Banks",
  "Paranoia Agent",
  "Party Down",
  "Penny Dreadful",
  "Penny Dreadful: City of Angels",
  "Pennyworth",
  "Percy Jackson and the Olympians",
  "Person of Interest",
  "Peyton Place",
  "Picket Fences",
  "Poker Face",
  "Poldark (1975)",
  "Poldark (2015)",
  "Pose",
  "Power",
  "Power Book II: Ghost",
  "Preacher",
  "Pretty Little Liars",
  "Pretty Little Liars: Original Sin",
  "Pride and Prejudice (1995)",
  "Psych",
  "Pushing Daisies",
  "Quantum Leap (1989)",
  "Quantum Leap (2022)",
  "Queer as Folk (UK)",
  "Queer as Folk (US 2000)",
  "Queer Eye",
  "Quincy, M.E.",
  "Ramy",
  "Ray Donovan",
  "Reacher",
  "Reba",
  "Rectify",
  "Red Dwarf",
  "Remington Steele",
  "Reservation Dogs",
  "Revenge",
  "Rizzoli & Isles",
  "Robot Chicken",
  "Rome",
  "Rookie Blue",
  "Roots (1977)",
  "Roots (2016)",
  "Roseanne",
  "Rowan & Martin's Laugh-In",
  "Rules of Engagement",
  "Runaways",
  "Sailor Moon",
  "Samurai Champloo",
  "Sanford and Son",
  "Santa Clarita Diet",
  "Saved by the Bell (1989)",
  "Saved by the Bell (2020)",
  "Scream Queens",
  "Search Party",
  "Secret City",
  "Secret Invasion",
  "Sense and Sensibility (2008)",
  "Sex and the City",
  "Sex Education",
  "Shadow and Bone",
  "Shadowhunters",
  "Shameless (UK)",
  "Shameless (US)",
  "Sharp Objects",
  "She-Hulk: Attorney at Law",
  "Shōgun (1980)",
  "Shōgun (2024)",
  "Silo",
  "Skins (UK)",
  "Sleepy Hollow",
  "Sliders",
  "Slow Horses",
  "Sneaky Pete",
  "Snowfall",
  "Soap",
  "Southland",
  "Space: 1999",
  "Spaced",
  "Spin City",
  "Spooks",
  "St. Elsewhere",
  "Star Trek: Deep Space Nine",
  "Star Trek: Discovery",
  "Star Trek: Enterprise",
  "Star Trek: Lower Decks",
  "Star Trek: Picard",
  "Star Trek: Strange New Worlds",
  "Star Trek: The Next Generation",
  "Star Trek: The Original Series",
  "Star Trek: Voyager",
  "Stargate Atlantis",
  "Stargate SG-1",
  "Stargate Universe",
  "Starsky & Hutch",
  "Station 19",
  "Station Eleven",
  "Steins;Gate",
  "Step by Step",
  "Strike Back",
  "Suburra: Blood on Rome",
  "Superstore",
  "Survivor",
  "Sweet Tooth",
  "Switched at Birth",
  "S.W.A.T. (1975)",
  "S.W.A.T. (2017)",
  "Taboo",
  "Tales from the Crypt",
  "Tales from the Loop",
  "Taxi",
  "That '70s Show",
  "That '90s Show",
  "The A-Team",
  "The Affair",
  "The Alienist",
  "The Andy Griffith Show",
  "The Avengers (1961)",
  "The Beverly Hillbillies",
  "The Bletchley Circle",
  "The Borgias",
  "The Brady Bunch",
  "The Bridge (Bron/Broen)",
  "The Bridge (US)",
  "The Capture",
  "The Chi",
  "The Closer",
  "The Conners",
  "The Cosby Show",
  "The Curse",
  "The Daily Show",
  "The Deuce",
  "The Dick Van Dyke Show",
  "The Diplomat",
  "The Dukes of Hazzard",
  "The Fall",
  "The Flight Attendant",
  "The Fosters",
  "The Fresh Prince of Bel-Air",
  "The Fugitive (1963)",
  "The Golden Girls",
  "The Goldbergs",
  "The Good Fight",
  "The Good Wife",
  "The Great",
  "The Inbetweeners (UK)",
  "The Inbetweeners (US)",
  "The IT Crowd",
  "The Jeffersons",
  "The Killing (2011)",
  "The Knick",
  "The L Word",
  "The Leftovers",
  "The Man in the High Castle",
  "The Mary Tyler Moore Show",
  "The Middle",
  "The Mighty Boosh",
  "The Muppet Show",
  "The Munsters",
  "The Nanny",
  "The Newsroom",
  "The Night Agent",
  "The Night Manager",
  "The Night Of",
  "The OA",
  "The Odd Couple (1970)",
  "The Odd Couple (2015)",
  "The Old Man",
  "The Outer Limits (1963)",
  "The Outer Limits (1995)",
  "The Pacific",
  "The Practice",
  "The Prisoner (1967)",
  "The Prisoner (2009)",
  "The Promised Neverland",
  "The Punisher",
  "The Righteous Gemstones",
  "The Rockford Files",
  "The Rookie",
  "The Sandman",
  "The Sinner",
  "The Stand (1994)",
  "The Stand (2020)",
  "The Terror",
  "The Thick of It",
  "The Tudors",
  "The West Wing",
  "The Wonder Years (1988)",
  "The Wonder Years (2021)",
  "Third Watch",
  "This Is Us",
  "Tokyo Vice",
  "Top Boy",
  "Torchwood",
  "Trailer Park Boys",
  "Trapped",
  "Treme",
  "Unbreakable Kimmy Schmidt",
  "Under the Banner of Heaven",
  "Unsolved Mysteries (1987)",
  "Unsolved Mysteries (2020)",
  "Utopia (UK)",
  "Utopia (US)",
  "V (1983)",
  "V (2009)",
  "Veronica Mars",
  "Vikings",
  "Vikings: Valhalla",
  "Walker, Texas Ranger",
  "Warehouse 13",
  "Weeds",
  "What We Do in the Shadows",
  "Whitechapel",
  "White Collar",
  "Who's the Boss?",
  "Will & Grace",
  "Winning Time: The Rise of the Lakers Dynasty",
  "Without a Trace",
  "Workaholics",
  "Xena: Warrior Princess",
  "Young Sheldon",
  "Your Honor",
  "Yu Yu Hakusho",
  "ZeroZeroZero"
];