const movieTitles = [
  "10 Things I Hate About You",
  "12 Angry Men",
  "1917",
  "2001: A Space Odyssey",
  "21 Jump Street",
  "22 Jump Street",
  "28 Days Later",
  "300",
  "500 Days of Summer",
  "A Clockwork Orange",
  "A Nightmare on Elm Street (1984)",
  "A Nightmare on Elm Street (2010)",
  "A Quiet Place",
  "A Quiet Place Part II",
  "A Star is Born (1937)",
  "A Star is Born (1976)",
  "A Star is Born (2018)",
  "Aladdin (1992)",
  "Aladdin (2019)",
  "Alien",
  "Aliens",
  "Alice in Wonderland (1951)",
  "Alice in Wonderland (2010)",
  "Amélie",
  "American Beauty",
  "American Psycho",
  "Anchorman: The Legend of Ron Burgundy",
  "Ant-Man",
  "Ant-Man and the Wasp",
  "Ant-Man and the Wasp: Quantumania",
  "Apollo 13",
  "Aquaman",
  "Arrival",
  "Avatar",
  "Avatar: The Way of Water",
  "Avengers: Age of Ultron",
  "Avengers: Endgame",
  "Avengers: Infinity War",
  "Baby Driver",
  "Back to the Future",
  "Back to the Future Part II",
  "Back to the Future Part III",
  "Batman (1989)",
  "Batman Begins",
  "Batman v Superman: Dawn of Justice",
  "Beauty and the Beast (1991)",
  "Beauty and the Beast (2017)",
  "Beetlejuice",
  "Big Hero 6",
  "Birdman",
  "Black Panther",
  "Black Panther: Wakanda Forever",
  "Black Swan",
  "Blade Runner",
  "Blade Runner 2049",
  "Bohemian Rhapsody",
  "Brave",
  "Braveheart",
  "Captain America: Civil War",
  "Captain America: The First Avenger",
  "Captain America: The Winter Soldier",
  "Captain Marvel",
  "Cars",
  "Cars 2",
  "Cars 3",
  "Casablanca",
  "Casino",
  "Casino Royale (2006)",
  "Cast Away",
  "Catch Me If You Can",
  "Charlie and the Chocolate Factory (2005)",
  "Citizen Kane",
  "City of God",
  "Clueless",
  "Coco",
  "Deadpool",
  "Deadpool 2",
  "Despicable Me",
  "Despicable Me 2",
  "Despicable Me 3",
  "Die Hard",
  "Django Unchained",
  "Doctor Strange",
  "Doctor Strange in the Multiverse of Madness",
  "Donnie Darko",
  "Dune (1984)",
  "Dune (2021)",
  "Dune: Part Two",
  "Dunkirk",
  "E.T. the Extra-Terrestrial",
  "Edge of Tomorrow",
  "Edward Scissorhands",
  "Eternal Sunshine of the Spotless Mind",
  "Everything Everywhere All at Once",
  "Ex Machina",
  "Fantastic Beasts and Where to Find Them",
  "Fargo",
  "Ferris Bueller's Day Off",
  "Fight Club",
  "Finding Dory",
  "Finding Nemo",
  "Forrest Gump",
  "Frozen",
  "Frozen II",
  "Full Metal Jacket",
  "Get Out",
  "Ghostbusters (1984)",
  "Ghostbusters (2016)",
  "Gladiator",
  "Godzilla (1954)",
  "Godzilla (2014)",
  "Gone Girl",
  "Good Will Hunting",
  "GoodFellas",
  "Gravity",
  "Guardians of the Galaxy",
  "Guardians of the Galaxy Vol. 2",
  "Guardians of the Galaxy Vol. 3",
  "Hacksaw Ridge",
  "Halloween (1978)",
  "Halloween (2018)",
  "Harry Potter and the Chamber of Secrets",
  "Harry Potter and the Deathly Hallows: Part 1",
  "Harry Potter and the Deathly Hallows: Part 2",
  "Harry Potter and the Goblet of Fire",
  "Harry Potter and the Half-Blood Prince",
  "Harry Potter and the Order of the Phoenix",
  "Harry Potter and the Philosopher's Stone",
  "Harry Potter and the Prisoner of Azkaban",
  "Heat",
  "Her",
  "Hereditary",
  "How to Train Your Dragon",
  "I Am Legend",
  "Ice Age",
  "Inception",
  "Indiana Jones and the Raiders of the Lost Ark",
  "Inglourious Basterds",
  "Inside Out",
  "Interstellar",
  "Iron Man",
  "Iron Man 2",
  "Iron Man 3",
  "It (1990)",
  "It (2017)",
  "It Chapter Two",
  "Jaws",
  "John Wick",
  "John Wick: Chapter 2",
  "John Wick: Chapter 3 - Parabellum",
  "John Wick: Chapter 4",
  "Joker",
  "Jumanji (1995)",
  "Jumanji: Welcome to the Jungle",
  "Jurassic Park",
  "Jurassic World",
  "Kill Bill: Vol. 1",
  "Kill Bill: Vol. 2",
  "King Kong (1933)",
  "King Kong (2005)",
  "Kingsman: The Secret Service",
  "Knives Out",
  "Knives Out: Glass Onion",
  "L.A. Confidential",
  "La La Land",
  "Les Misérables (2012)",
  "Life Is Beautiful",
  "Little Miss Sunshine",
  "Little Women (1994)",
  "Little Women (2019)",
  "Logan",
  "Logan Lucky",
  "Lord of the Rings: The Fellowship of the Ring",
  "Lord of the Rings: The Return of the King",
  "Lord of the Rings: The Two Towers",
  "Lucy",
  "Léon: The Professional",
  "Mad Max: Fury Road",
  "Man of Steel",
  "Mean Girls",
  "Memento",
  "Men in Black",
  "Midsommar",
  "Monsters, Inc.",
  "No Country for Old Men",
  "Now You See Me",
  "Ocean's Eleven (1960)",
  "Ocean's Eleven (2001)",
  "Once Upon a Time... in Hollywood",
  "Oppenheimer",
  "Parasite",
  "Passengers",
  "Pirates of the Caribbean: At World's End",
  "Pirates of the Caribbean: Dead Man's Chest",
  "Pirates of the Caribbean: On Stranger Tides",
  "Pirates of the Caribbean: The Curse of the Black Pearl",
  "Planet of the Apes (1968)",
  "Planet of the Apes (2001)",
  "Platoon",
  "Prisoners",
  "Pulp Fiction",
  "Ratatouille",
  "Ready Player One",
  "Requiem for a Dream",
  "Reservoir Dogs",
  "Return of the Jedi",
  "RoboCop (1987)",
  "RoboCop (2014)",
  "Rogue One: A Star Wars Story",
  "Saving Private Ryan",
  "Scarface (1983)",
  "Schindler's List",
  "Scream (1996)",
  "Se7en",
  "Sherlock Holmes",
  "Shrek",
  "Shrek 2",
  "Shutter Island",
  "Sicario",
  "Snatch",
  "Spider-Man (2002)",
  "Spider-Man 2",
  "Spider-Man 3",
  "Spider-Man: Across the Spider-Verse",
  "Spider-Man: Far From Home",
  "Spider-Man: Homecoming",
  "Spider-Man: Into the Spider-Verse",
  "Spider-Man: No Way Home",
  "Spirited Away",
  "Split",
  "Star Wars: Episode I - The Phantom Menace",
  "Star Wars: Episode II - Attack of the Clones",
  "Star Wars: Episode III - Revenge of the Sith",
  "Star Wars: Episode IV - A New Hope",
  "Star Wars: Episode V - The Empire Strikes Back",
  "Star Wars: The Force Awakens",
  "Star Wars: The Last Jedi",
  "Suicide Squad (2016)",
  "Superbad",
  "Taxi Driver",
  "Terminator 2: Judgment Day",
  "The Amazing Spider-Man (2012)",
  "The Amazing Spider-Man 2",
  "The Avengers",
  "The Big Lebowski",
  "The Breakfast Club",
  "The Dark Knight",
  "The Dark Knight Rises",
  "The Departed",
  "The Devil Wears Prada",
  "The Fifth Element",
  "The Godfather",
  "The Godfather Part II",
  "The Grand Budapest Hotel",
  "The Great Gatsby (2013)",
  "The Green Mile",
  "The Hateful Eight",
  "The Hobbit: An Unexpected Journey",
  "The Hobbit: The Battle of the Five Armies",
  "The Hobbit: The Desolation of Smaug",
  "The Hunger Games",
  "The Hunger Games: Catching Fire",
  "The Hunger Games: Mockingjay - Part 1",
  "The Hunger Games: Mockingjay - Part 2",
  "The Imitation Game",
  "The Incredibles",
  "The Intouchables",
  "The Jungle Book (1966)",
  "The Jungle Book (2016)",
  "The Lion King (1994)",
  "The Lion King (2019)",
  "The Martian",
  "The Matrix",
  "The Maze Runner",
  "The Mummy (1999)",
  "The Mummy (2017)",
  "The Prestige",
  "The Revenant",
  "The Shawshank Redemption",
  "The Shining",
  "The Silence of the Lambs",
  "The Social Network",
  "The Suicide Squad (2021)",
  "The Terminator",
  "The Truman Show",
  "The Untouchables",
  "The Usual Suspects",
  "The Wolf of Wall Street",
  "There Will Be Blood",
  "Thor",
  "Thor: Love and Thunder",
  "Thor: Ragnarok",
  "Thor: The Dark World",
  "Titanic",
  "Top Gun (1986)",
  "Top Gun: Maverick",
  "Total Recall (1990)",
  "Total Recall (2012)",
  "Toy Story",
  "Toy Story 2",
  "Toy Story 3",
  "Toy Story 4",
  "Tron (1982)",
  "Tron: Legacy (2010)",
  "True Grit (1969)",
  "True Grit (2010)",
  "Twilight",
  "Up",
  "V for Vendetta",
  "Venom",
  "WALL-E",
  "West Side Story (1961)",
  "West Side Story (2021)",
  "Whiplash",
  "Willy Wonka & the Chocolate Factory (1971)",
  "Wonder Woman",
  "World War Z",
  "X-Men: Days of Future Past",
  "Zodiac",
  "Zootopia",
  "10 Cloverfield Lane",
  "12 Monkeys",
  "127 Hours",
  "13 Assassins",
  "13 Going on 30",
  "1408",
  "2 Fast 2 Furious",
  "2012",
  "21 Grams",
  "25th Hour",
  "28 Weeks Later",
  "30 Days of Night",
  "300: Rise of an Empire",
  "3:10 to Yuma (1957)",
  "3:10 to Yuma (2007)",
  "42",
  "47 Ronin",
  "50 First Dates",
  "8 Mile",
  "A Beautiful Mind",
  "A Bronx Tale",
  "A Bug's Life",
  "A Few Good Men",
  "A Fish Called Wanda",
  "A Monster Calls",
  "A Quiet Place: Day One",
  "About Time",
  "Ace Ventura: Pet Detective",
  "Ace Ventura: When Nature Calls",
  "Air Force One",
  "Airplane!",
  "Alien 3",
  "Alien: Resurrection",
  "Alien: Covenant",
  "Alien: Romulus",
  "All About Eve",
  "All Quiet on the Western Front (1930)",
  "All Quiet on the Western Front (2022)",
  "Almost Famous",
  "Alpha Dog",
  "American Gangster",
  "American History X",
  "American Hustle",
  "American Pie",
  "American Sniper",
  "Anatomy of a Fall",
  "Annihilation",
  "Apocalypse Now",
  "Armageddon",
  "As Good as It Gets",
  "Asteroid City",
  "Austin Powers: International Man of Mystery",
  "Austin Powers: The Spy Who Shagged Me",
  "Austin Powers in Goldmember",
  "Babylon",
  "Bad Boys (1995)",
  "Bad Boys II",
  "Bad Boys for Life",
  "Bad Boys: Ride or Die",
  "Bambi",
  "Barbie",
  "Barton Fink",
  "Basic Instinct",
  "Batman Forever",
  "Batman Returns",
  "Batman & Robin",
  "Being John Malkovich",
  "Bicycle Thieves",
  "Big Daddy",
  "Big Fish",
  "Big Trouble in Little China",
  "Bill & Ted's Excellent Adventure",
  "Black Hawk Down",
  "Black Mass",
  "Blade (1998)",
  "Blade II",
  "Blade: Trinity",
  "Blazing Saddles",
  "Blow",
  "Blue Velvet",
  "Body Heat",
  "Boogie Nights",
  "Borat",
  "Boyhood",
  "Boyz n the Hood",
  "Bram Stoker's Dracula",
  "Bridge of Spies",
  "Brokeback Mountain",
  "Bullet Train",
  "Burn After Reading",
  "Caddyshack",
  "Cape Fear (1962)",
  "Cape Fear (1991)",
  "Captain Phillips",
  "Carlito's Way",
  "Carrie (1976)",
  "Carrie (2013)",
  "Casino Royale (1967)",
  "Chappie",
  "Children of Men",
  "Chinatown",
  "Chocolat",
  "Cinderella (1950)",
  "Cinderella (2015)",
  "Cloverfield",
  "Collateral",
  "Commando",
  "Con Air",
  "Conan the Barbarian (1982)",
  "Conan the Destroyer",
  "Constantine",
  "Contact",
  "Coraline",
  "Corpse Bride",
  "Crash (1996)",
  "Crash (2004)",
  "Creed",
  "Creed II",
  "Creed III",
  "Crouching Tiger, Hidden Dragon",
  "Dark City",
  "Dawn of the Dead (1978)",
  "Dawn of the Dead (2004)",
  "Dawn of the Planet of the Apes",
  "Days of Thunder",
  "Dazed and Confused",
  "Dead Poets Society",
  "Death Proof",
  "Deep Impact",
  "Deliverance",
  "Demolition Man",
  "District 9",
  "Doctor Zhivago",
  "Dodgeball: A True Underdog Story",
  "Dog Day Afternoon",
  "Downton Abbey (2019)",
  "Dr. No",
  "Dr. Strangelove",
  "Dracula (1931)",
  "Drive",
  "Dumbo (1941)",
  "Dumbo (2019)",
  "Easy Rider",
  "El Camino: A Breaking Bad Movie",
  "Elf",
  "Empire of the Sun",
  "Enemy at the Gates",
  "Enter the Dragon",
  "Eraserhead",
  "Escape from New York",
  "Evil Dead (1981)",
  "Evil Dead II",
  "Evil Dead (2013)",
  "Evil Dead Rise",
  "Excalibur",
  "Face/Off",
  "Fall",
  "Fantastic Mr. Fox",
  "Fast & Furious (2009)",
  "Fast & Furious 6",
  "Fast Five",
  "Fatal Attraction",
  "First Blood",
  "First Man",
  "Flight",
  "Ford v Ferrari",
  "Four Weddings and a Funeral",
  "Frankenstein (1931)",
  "Freaky Friday (2003)",
  "Free Guy",
  "Friday",
  "Friday the 13th (1980)",
  "Friday the 13th (2009)",
  "From Dusk Till Dawn",
  "From Russia with Love",
  "Galaxy Quest",
  "Gangs of New York",
  "Gattaca",
  "Ghost (1990)",
  "Ghost in the Shell (1995)",
  "Ghost in the Shell (2017)",
  "Godzilla Minus One",
  "GoldenEye",
  "Goldfinger",
  "Good Morning, Vietnam",
  "Good Night, and Good Luck.",
  "Gran Torino",
  "Grease",
  "Green Book",
  "Green Lantern",
  "Gremlins",
  "Gremlins 2: The New Batch",
  "Groundhog Day",
  "Hairspray (1988)",
  "Hairspray (2007)",
  "Halloween II (1981)",
  "Hancock",
  "Hard Boiled",
  "Harold & Kumar Go to White Castle",
  "Harry Brown",
  "Hellboy (2004)",
  "Hellboy (2019)",
  "High Fidelity",
  "High Noon",
  "Hit Man",
  "Hocus Pocus",
  "Home Alone",
  "Home Alone 2: Lost in New York",
  "Hook",
  "Hostel",
  "Hotel Rwanda",
  "House of Flying Daggers",
  "How to Train Your Dragon 2",
  "How to Train Your Dragon: The Hidden World",
  "Hugo",
  "Hulk (2003)",
  "I, Robot",
  "In the Heat of the Night",
  "In the Mood for Love",
  "Incendies",
  "Independence Day",
  "Independence Day: Resurgence",
  "Indiana Jones and the Temple of Doom",
  "Indiana Jones and the Last Crusade",
  "Indiana Jones and the Kingdom of the Crystal Skull",
  "Indiana Jones and the Dial of Destiny",
  "Infernal Affairs",
  "Insidious",
  "Insomnia (2002)",
  "Interview with the Vampire",
  "Into the Wild",
  "Isle of Dogs",
  "Jackie Brown",
  "Jarhead",
  "Jerry Maguire",
  "John Carter",
  "Jojo Rabbit",
  "Judas and the Black Messiah",
  "Jumanji: The Next Level",
  "Juno",
  "Killers of the Flower Moon",
  "Kingdom of Heaven",
  "Kingdom of the Planet of the Apes",
  "Kiss Kiss Bang Bang",
  "Knocked Up",
  "Kung Fu Hustle",
  "Kung Fu Panda",
  "Kung Fu Panda 2",
  "Kung Fu Panda 3",
  "Kung Fu Panda 4",
  "Labyrinth",
  "Lady Bird",
  "Lars and the Real Girl",
  "Lawrence of Arabia",
  "Legally Blonde",
  "Lethal Weapon",
  "Lethal Weapon 2",
  "Lethal Weapon 3",
  "Lethal Weapon 4",
  "Liar Liar",
  "Life of Pi",
  "Live Free or Die Hard",
  "Lock, Stock and Two Smoking Barrels",
  "Looper",
  "Lord of War",
  "Lost in Translation",
  "Love Actually",
  "Magnolia",
  "Maleficent",
  "Mamma Mia!",
  "Manchester by the Sea",
  "Manhattan",
  "Marley & Me",
  "Mary Poppins",
  "Match Point",
  "Megamind",
  "Men in Black II",
  "Men in Black 3",
  "Men in Black: International",
  "Midnight Cowboy",
  "Midnight in Paris",
  "Minority Report",
  "Misery",
  "Mission: Impossible",
  "Mission: Impossible II",
  "Mission: Impossible III",
  "Mission: Impossible - Ghost Protocol",
  "Mission: Impossible - Rogue Nation",
  "Mission: Impossible - Fallout",
  "Mission: Impossible - Dead Reckoning",
  "Moneyball",
  "Monsters University",
  "Monty Python and the Holy Grail",
  "Monty Python's Life of Brian",
  "Moon",
  "Moonlight",
  "Moonrise Kingdom",
  "Moulin Rouge!",
  "Mulholland Drive",
  "Munich",
  "Mystic River",
  "National Lampoon's Christmas Vacation",
  "National Lampoon's Vacation",
  "National Treasure",
  "National Treasure: Book of Secrets",
  "Network",
  "Night at the Museum",
  "Nightcrawler",
  "No Time to Die",
  "Nobody",
  "Nomadland",
  "North by Northwest",
  "Nosferatu (1922)",
  "Notting Hill",
  "Oldboy (2003)",
  "Oldboy (2013)",
  "Once Upon a Time in America",
  "Once Upon a Time in the West",
  "One Flew Over the Cuckoo's Nest",
  "Onward",
  "Open Range",
  "Over the Hedge",
  "Pacific Rim",
  "Pan's Labyrinth",
  "Panic Room",
  "Patton",
  "Pearl Harbor",
  "Pee-wee's Big Adventure",
  "Percy Jackson & the Olympians: The Lightning Thief",
  "Pet Sematary (1989)",
  "Pet Sematary (2019)",
  "Philadelphia",
  "Pinocchio (1940)",
  "Pirates of the Caribbean: Dead Men Tell No Tales",
  "Pitch Black",
  "Pitch Perfect",
  "Poltergeist (1982)",
  "Poltergeist (2015)",
  "Predator (1987)",
  "Predator 2",
  "Predators",
  "Prey (2022)",
  "Pride & Prejudice (2005)",
  "Primal Fear",
  "Princess Mononoke",
  "Psycho (1960)",
  "Psycho (1998)",
  "Public Enemies",
  "Puss in Boots (2011)",
  "Puss in Boots: The Last Wish",
  "Quantum of Solace",
  "Raging Bull",
  "Rain Man",
  "Raising Arizona",
  "Rambo (2008)",
  "Rambo: First Blood Part II",
  "Rambo III",
  "Rambo: Last Blood",
  "Rashomon",
  "Rear Window",
  "Rebel Without a Cause",
  "Red Dragon",
  "Remember the Titans",
  "Rise of the Planet of the Apes",
  "Road to Perdition",
  "Robin Hood: Prince of Thieves",
  "RoboCop 2",
  "RoboCop 3",
  "Rocky",
  "Rocky II",
  "Rocky III",
  "Rocky IV",
  "Rocky V",
  "Rocky Balboa",
  "Rope",
  "Rush",
  "Rush Hour",
  "Rush Hour 2",
  "Rush Hour 3",
  "Saw (2004)",
  "Saw II",
  "Saw III",
  "Saw X",
  "School of Rock",
  "Scott Pilgrim vs. the World",
  "Scream 2",
  "Scream 3",
  "Scream 4",
  "Scream (2022)",
  "Scream VI",
  "Seven Psychopaths",
  "Seven Samurai",
  "Shaun of the Dead",
  "Signs",
  "Sin City",
  "Singin' in the Rain",
  "Sky High",
  "Sleepy Hollow",
  "Slumdog Millionaire",
  "Soul",
  "Source Code",
  "Space Jam (1996)",
  "Spaceballs",
  "Spartacus (1960)",
  "Speed",
  "Spellbound",
  "Spotlight",
  "Stand by Me",
  "Star Trek (2009)",
  "Star Trek Into Darkness",
  "Star Trek Beyond",
  "Star Trek II: The Wrath of Khan",
  "Star Trek IV: The Voyage Home",
  "Starship Troopers",
  "Super 8",
  "Sweeney Todd: The Demon Barber of Fleet Street",
  "Taken",
  "Tangled",
  "Tarzan (1999)",
  "Team America: World Police",
  "Tenet",
  "The Abyss",
  "The Addams Family (1991)",
  "The Addams Family (2019)",
  "The Adventures of Tintin",
  "The Banshees of Inisherin",
  "The Batman (2022)",
  "The Big Short",
  "The Birds",
  "The Blair Witch Project",
  "The Blues Brothers",
  "The Book of Eli",
  "The Boondock Saints",
  "The Bourne Identity",
  "The Bourne Supremacy",
  "The Bourne Ultimatum",
  "The Bourne Legacy",
  "The Boy in the Striped Pyjamas",
  "The Bridge on the River Kwai",
  "The Cabin in the Woods",
  "The Chronicles of Narnia: The Lion, the Witch and the Wardrobe",
  "The Chronicles of Narnia: Prince Caspian",
  "The Chronicles of Narnia: The Voyage of the Dawn Treader",
  "The Conjuring 2",
  "The Crow (1994)",
  "The Crow (2024)",
  "The Curious Case of Benjamin Button",
  "The Da Vinci Code",
  "The Deer Hunter",
  "The Exorcist (1973)",
  "The Fast and the Furious (2001)",
  "The Fault in Our Stars",
  "The Fighter",
  "The French Connection",
  "The Fugitive",
  "The Girl with the Dragon Tattoo (2009)",
  "The Girl with the Dragon Tattoo (2011)",
  "The Gold Rush",
  "The Good, the Bad and the Ugly",
  "The Graduate",
  "The Grandmaster",
  "The Hudsucker Proxy",
  "The Hurt Locker",
  "The Illusionist",
  "The Invisible Man (1933)",
  "The Invisible Man (2020)",
  "The Iron Giant",
  "The Karate Kid (1984)",
  "The Karate Kid (2010)",
  "The King's Speech",
  "The Last Samurai",
  "The Lighthouse",
  "The Lobster",
  "The Lost World: Jurassic Park",
  "The Magnificent Seven (1960)",
  "The Magnificent Seven (2016)",
  "The Maltese Falcon",
  "The Mask (1994)",
  "The Master",
  "The Mitchells vs. the Machines",
  "The Naked Gun: From the Files of Police Squad!",
  "The Nightmare Before Christmas",
  "The Northman",
  "The Notebook",
  "The Others",
  "The Passion of the Christ",
  "The Perks of Being a Wallflower",
  "The Princess Bride",
  "The Producers (1967)",
  "The Producers (2005)",
  "The Raid: Redemption",
  "The Raid 2",
  "The Right Stuff",
  "The Ring (2002)",
  "The Road",
  "The Rock",
  "The Royal Tenenbaums",
  "The Secret Life of Walter Mitty (2013)",
  "The Sound of Music",
  "The Thing (1982)",
  "101 Dalmatians (1961)",
  "101 Dalmatians (1996)",
  "12 Years a Slave",
  "1492: Conquest of Paradise",
  "1984 (1984)",
  "20,000 Leagues Under the Sea (1954)",
  "2046",
  "21 (2008)",
  "27 Dresses",
  "3 Idiots",
  "30 Minutes or Less",
  "3000 Miles to Graceland",
  "40 Days and 40 Nights",
  "48 Hrs.",
  "50/50",
  "8½",
  "A Bridge Too Far",
  "A Christmas Carol (1951)",
  "A Christmas Carol (2009)",
  "A Christmas Story",
  "A Cure for Wellness",
  "A Ghost Story",
  "A Goofy Movie",
  "A Hard Day's Night",
  "A Haunting in Venice",
  "A History of Violence",
  "A Knight's Tale",
  "A Man Called Otto",
  "A Man for All Seasons",
  "A Most Violent Year",
  "A Night at the Opera",
  "A Passage to India",
  "A Prophet",
  "A River Runs Through It",
  "A Scanner Darkly",
  "A Serious Man",
  "A Simple Favor",
  "A Simple Plan",
  "A Streetcar Named Desire",
  "A Time to Kill",
  "A View to a Kill",
  "About a Boy",
  "About Schmidt",
  "Adaptation.",
  "Ad Astra",
  "After Hours",
  "Aftersun",
  "Air (2023)",
  "Akira",
  "Alien vs. Predator",
  "Alita: Battle Angel",
  "All of Us Strangers",
  "All the Money in the World",
  "All the President's Men",
  "Along Came a Spider",
  "Along Came Polly",
  "Amadeus",
  "Amistad",
  "An American Tail",
  "An American Werewolf in London",
  "Anatomy of a Murder",
  "Animal House",
  "Annabelle",
  "Annabelle Comes Home",
  "Annabelle: Creation",
  "Annie (1982)",
  "Annie Hall",
  "Antz",
  "Any Given Sunday",
  "Arachnophobia",
  "Argo",
  "Army of Darkness",
  "Army of the Dead",
  "Arthur Christmas",
  "As Above, So Below",
  "Assault on Precinct 13 (1976)",
  "Assault on Precinct 13 (2005)",
  "Atlantis: The Lost Empire",
  "Atonement",
  "Attack the Block",
  "Audition (1999)",
  "Bad Education (2004)",
  "Bad Education (2019)",
  "Bad Santa",
  "Bad Teacher",
  "Balto",
  "Barbarian",
  "Barry Lyndon",
  "Basic (2003)",
  "Battleship",
  "Be Kind Rewind",
  "Bean (1997)",
  "Beasts of No Nation",
  "Beasts of the Southern Wild",
  "Bedazzled (1967)",
  "Bedazzled (2000)",
  "Before Midnight",
  "Before Sunrise",
  "Before Sunset",
  "Belfast",
  "Belle (2021)",
  "Ben-Hur (1959)",
  "Ben-Hur (2016)",
  "Best in Show",
  "Better Off Dead",
  "Beverly Hills Cop",
  "Beverly Hills Cop II",
  "Beverly Hills Cop III",
  "Beverly Hills Cop: Axel F",
  "Big",
  "Big Momma's House",
  "Billy Elliot",
  "Billy Madison",
  "Bird Box",
  "Birds of Prey",
  "Black Adam",
  "Black Christmas (1974)",
  "Black Rain",
  "Black Sunday",
  "Black Widow",
  "BlacKkKlansman",
  "Blood Diamond",
  "Blood Simple",
  "Blow Out",
  "Blue Beetle",
  "Blue Jasmine",
  "Blue Ruin",
  "Blue Valentine",
  "Boiler Room",
  "Bolt",
  "Bone Tomahawk",
  "Bonnie and Clyde",
  "Booksmart",
  "Born on the Fourth of July",
  "Bottle Rocket",
  "Bound",
  "Bowfinger",
  "Boys Don't Cry",
  "Brassed Off",
  "Brazil",
  "Breakfast at Tiffany's",
  "Brick",
  "Bridesmaids",
  "Bridge to Terabithia",
  "Bridget Jones's Diary",
  "Bright",
  "Bringing Down the House",
  "Bringing Out the Dead",
  "Broadcast News",
  "Bronson",
  "Brother Bear",
  "Brothers (2009)",
  "Bruce Almighty",
  "Buffalo '66",
  "Bumblebee",
  "Buried",
  "Cabaret",
  "Candyman (1992)",
  "Candyman (2021)",
  "Can't Hardly Wait",
  "Capote",
  "Captain America: Brave New World",
  "Captain Fantastic",
  "Catch-22",
  "Cats (2019)",
  "Cell 211",
  "Central Intelligence",
  "Challengers",
  "Champion (1949)",
  "Changeling",
  "Chaos Walking",
  "Chariots of Fire",
  "Charlie Wilson's War",
  "Chef",
  "Chicken Run",
  "Chicken Run: Dawn of the Nugget",
  "Child's Play (1988)",
  "Child's Play (2019)",
  "Christine (1983)",
  "Chronicle",
  "Clash of the Titans (1981)",
  "Clash of the Titans (2010)",
  "Clerks",
  "Clerks II",
  "Cliffhanger",
  "Cloudy with a Chance of Meatballs",
  "Clue (1985)",
  "Cocaine Bear",
  "Cold Mountain",
  "Coming to America",
  "Coming 2 America",
  "Cop Land",
  "Cowboys & Aliens",
  "Crank",
  "Crank: High Voltage",
  "Crazy Rich Asians",
  "Crazy, Stupid, Love.",
  "Crimson Peak",
  "Crimson Tide",
  "Cujo",
  "Cure (1997)",
  "Dallas Buyers Club",
  "Dancer in the Dark",
  "Dark Phoenix",
  "Dark Skies",
  "Dark Water (2002)",
  "Darkest Hour",
  "Daylight",
  "Dead Man Walking",
  "Dead Silence",
  "Deadpool & Wolverine",
  "Dear Zachary: A Letter to a Son About His Father",
  "Death at a Funeral (2007)",
  "Death at a Funeral (2010)",
  "Death on the Nile (1978)",
  "Death on the Nile (2022)",
  "Death Race (2008)",
  "Deep Blue Sea",
  "Defiance",
  "Den of Thieves",
  "Despicable Me 4",
  "Detroit",
  "Devil (2010)",
  "Diamonds Are Forever",
  "Dick Tracy (1990)",
  "Die Another Day",
  "Dirty Dancing",
  "Dirty Harry",
  "Dirty Rotten Scoundrels",
  "Disobedience",
  "Divergent",
  "Insurgent",
  "Allegiant",
  "Dogville",
  "Don Jon",
  "Don't Breathe",
  "Don't Look Now",
  "Don't Look Up",
  "Donnie Brasco",
  "Doom (2005)",
  "Downfall (2004)",
  "Dr. Dolittle (1998)",
  "Dracula Untold",
  "Drag Me to Hell",
  "Dragonheart",
  "Dredd",
  "Drive My Car",
  "Duck Soup",
  "Dumb and Dumber",
  "Dumb and Dumber To",
  "Eagle Eye",
  "Early Man",
  "Eastern Promises",
  "Easy A",
  "Ed Wood",
  "El Mariachi",
  "Election",
  "Elemental",
  "Elizabeth (1998)",
  "Elizabeth: The Golden Age",
  "Elysium",
  "Encanto",
  "Enchanted",
  "Ender's Game",
  "Enemy (2013)",
  "Equilibrium",
  "Erin Brockovich",
  "Escape from Alcatraz",
  "Escape from L.A.",
  "EuroTrip",
  "Eurovision Song Contest: The Story of Fire Saga",
  "Evan Almighty",
  "Event Horizon",
  "Everest",
  "Experimenter",
  "Extremely Wicked, Shockingly Evil and Vile",
  "Eyes Wide Shut",
  "Falling Down",
  "Fast & Furious Presents: Hobbs & Shaw",
  "Fast X",
  "Father of the Bride (1991)",
  "Fences",
  "FernGully: The Last Rainforest",
  "Filth",
  "Final Destination",
  "Final Destination 2",
  "Final Destination 3",
  "First Reformed",
  "Fistful of Dollars, A",
  "Flags of Our Fathers",
  "Flee",
  "Flushed Away",
  "Footloose (1984)",
  "Footloose (2011)",
  "For a Few Dollars More",
  "Forgetting Sarah Marshall",
  "Four Lions",
  "Foxcatcher",
  "Fracture",
  "Frankenweenie (2012)",
  "Freddy vs. Jason",
  "Freedom Writers",
  "Friday the 13th Part 2",
  "Friday the 13th Part III",
  "Fried Green Tomatoes",
  "Frost/Nixon",
  "Funny Games (1997)",
  "Funny Games (2007)",
  "Furiosa: A Mad Max Saga",
  "G.I. Joe: Retaliation",
  "G.I. Joe: The Rise of Cobra",
  "Game Night",
  "Gandhi",
  "Gemini Man",
  "Geostorm",
  "Gerald's Game",
  "Get Him to the Greek",
  "Ghost Rider",
  "Ghost Rider: Spirit of Vengeance",
  "Ghost World",
  "Ghosts of Mars",
  "Girl, Interrupted",
  "Girls Trip",
  "Glengarry Glen Ross",
  "Glory (1989)",
  "Gnomeo & Juliet",
  "Gods of Egypt",
  "Godzilla (1998)",
  "Godzilla vs. Kong",
  "Godzilla x Kong: The New Empire",
  "Good Time",
  "Goodnight Mommy (2014)",
  "Gothic",
  "Gran Turismo",
  "Green Room",
  "Grown Ups",
  "Grown Ups 2",
  "Halloween (2007)",
  "Halloween H20: 20 Years Later",
  "Halloween Kills",
  "Halloween Ends",
  "Happy Death Day",
  "Happy Death Day 2U",
  "Happy Gilmore",
  "Hard Eight",
  "Hardcore Henry",
  "Harriet",
  "He's Just Not That Into You",
  "Heavenly Creatures",
  "Hell or High Water",
  "Hellboy II: The Golden Army",
  "Hellraiser (1987)",
  "Hellraiser (2022)",
  "Hercules (1997)",
  "Hercules (2014)",
  "Hidden Figures",
  "High Plains Drifter",
  "Highlander",
  "Hillbilly Elegy",
  "Hitch",
  "Holes",
  "Home (2015)",
  "Honey, I Shrunk the Kids",
  "Horrible Bosses",
  "Horrible Bosses 2",
  "Horton Hears a Who!",
  "Host (2020)",
  "Hot Fuzz",
  "Hot Rod",
  "Hot Tub Time Machine",
  "Hotel Mumbai",
  "Hotel Transylvania",
  "Hotel Transylvania 2",
  "House of 1000 Corpses",
  "House of Gucci",
  "House of Wax (1953)",
  "House of Wax (2005)",
  "House Party (1990)",
  "How the Grinch Stole Christmas (2000)",
  "How to Lose a Guy in 10 Days",
  "Hunt for the Wilderpeople",
  "I Am Number Four",
  "I Know What You Did Last Summer",
  "I Love You, Man",
  "I Now Pronounce You Chuck & Larry",
  "I Saw the Devil",
  "I Spit on Your Grave (1978)",
  "I, Frankenstein",
  "I, Tonya",
  "Ice Age: Dawn of the Dinosaurs",
  "Ice Age: The Meltdown",
  "Identity",
  "Identity Thief",
  "Idiocracy",
  "Igor",
  "Immortals",
  "In Bruges",
  "In Cold Blood",
  "In the Mouth of Madness",
  "In the Name of the Father",
  "In Time",
  "Inherit the Wind",
  "Inside Man",
  "Inside Out 2",
  "Insidious: Chapter 2",
  "Insidious: Chapter 3",
  "Insidious: The Red Door",
  "Inherent Vice",
  "Interstella 5555",
  "Invasion of the Body Snatchers (1956)",
  "Invasion of the Body Snatchers (1978)",
  "Invictus",
  "It Follows",
  "J. Edgar",
  "Jack Reacher",
  "Jack Reacher: Never Go Back",
  "Jack the Giant Slayer",
  "Jackass Forever",
  "Jackass Number Two",
  "Jackass: The Movie",
  "Jackie",
  "Jacob's Ladder (1990)",
  "Jennifer's Body",
  "JFK",
  "Joy Ride (2023)",
  "Judgment at Nuremberg",
  "Julie & Julia",
  "Jupiter Ascending",
  "Just Friends",
  "Just Go with It",
  "Just Mercy",
  "Kick-Ass",
  "Kick-Ass 2",
  "Kindergarten Cop",
  "King Arthur: Legend of the Sword",
  "King Richard",
  "Kingdom of the Spiders",
  "Kingpin",
  "Kinsey",
  "Klaus",
  "Kong: Skull Island",
  "Kubo and the Two Strings",
  "Lady Macbeth",
  "Lake Mungo",
  "Lara Croft: Tomb Raider (2001)",
  "Last Action Hero",
  "Last Night in Soho",
  "Late Night with the Devil",
  "Law Abiding Citizen",
  "Lawless",
  "Leave No Trace",
  "Legally Blonde 2: Red, White & Blonde",
  "Lemony Snicket's A Series of Unfortunate Events",
  "Let Me In",
  "Let the Right One In",
  "Licorice Pizza",
  "Lights Out",
  "Limitless",
  "Lincoln",
  "Lion (2016)",
  "Little Children",
  "Little Fockers",
  "Lockout",
  "London Has Fallen",
  "Lone Survivor",
  "Longlegs",
  "Look Who's Talking",
  "Love & Other Drugs",
  "Loving",
  "Luca",
  "M3GAN",
  "MacGruber",
  "Mad Max (1979)",
  "Mad Max 2: The Road Warrior",
  "Mad Max Beyond Thunderdome",
  "Madame Web",
  "Madagascar",
  "Madagascar 3: Europe's Most Wanted",
  "Madagascar: Escape 2 Africa",
  "Major League",
  "Malcolm X",
  "Malignant",
  "Mallrats",
  "Marriage Story",
  "Mary Poppins Returns",
  "Mary Queen of Scots (2018)",
  "Master and Commander: The Far Side of the World",
  "May December",
  "Mean Girls (2024)",
  "Meet the Fockers",
  "Meet the Parents",
  "Meet the Robinsons",
  "Meg 2: The Trench",
  "Midnight Express",
  "Milk",
  "Million Dollar Baby",
  "Minari",
  "Minions",
  "Minions: The Rise of Gru",
  "Miracle (2004)"
];